import { t } from 'i18next'
import {
  Bathroom,
  Bedroom,
  Closet,
  DiningRoom,
  Entryway,
  Garage,
  GuestBedroom,
  Hallway,
  Kitchen,
  Laundry,
  LivingRoom,
  MasterBedroom,
  Mudroom,
  Office,
  Patio,
  Structure,
  Theatre,
} from '../../assets/images/rooms'

export const RoomsList = [
  {
    icon: Bathroom,
    id: 'bathroom',
    index: 0,
    label: t('rooms.bathroom'),
  },
  {
    icon: Bedroom,
    id: 'bedroom',
    index: 1,
    label: t('rooms.bedroom'),
  },
  {
    icon: Closet,
    id: 'closet',
    index: 2,
    label: t('rooms.closet'),
  },
  {
    icon: DiningRoom,
    id: 'dining-room',
    index: 3,
    label: t('rooms.dining'),
  },
  {
    icon: Entryway,
    id: 'entryway',
    index: 4,
    label: t('rooms.entryway'),
  },
  {
    icon: Garage,
    id: 'garage',
    index: 5,
    label: t('rooms.garage'),
  },
  {
    icon: GuestBedroom,
    id: 'guest-bedroom',
    index: 6,
    label: t('rooms.guestBedroom'),
  },
  {
    icon: Hallway,
    id: 'hallway',
    index: 7,
    label: t('rooms.hallway'),
  },
  {
    icon: Kitchen,
    id: 'kitchen',
    index: 8,
    label: t('rooms.kitchen'),
  },
  {
    icon: Laundry,
    id: 'laundry',
    index: 9,
    label: t('rooms.laundry'),
  },
  {
    icon: LivingRoom,
    id: 'living-room',
    index: 10,
    label: t('rooms.living'),
  },
  {
    icon: MasterBedroom,
    id: 'master-bedroom',
    index: 11,
    label: t('rooms.masterBedroom'),
  },
  {
    icon: Mudroom,
    id: 'mudroom',
    index: 12,
    label: t('rooms.mudroom'),
  },
  {
    icon: Office,
    id: 'office',
    index: 13,
    label: t('rooms.office'),
  },
  {
    icon: Patio,
    id: 'patio',
    index: 14,
    label: t('rooms.patio'),
  },
  {
    icon: Structure,
    id: 'structure',
    index: 15,
    label: t('rooms.structure'),
  },
  {
    icon: Theatre,
    id: 'theatre',
    index: 16,
    label: t('rooms.theatre'),
  },
]
